name = "fomafamily-v2"
main = ".open-next/worker.js"
compatibility_date = "2026-07-02"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fomawebsitedatabase"
database_id = "07579979-b2fe-4c94-9d33-7c0936b4e9a2"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "fomawebsitev2"
