/**
 * Fix HTML-entity encoding left over from OpenCart in D1 data.
 *
 * Policy:
 *  - categories.name / products.name: plain-text fields (React escapes on
 *    render) → decode repeatedly until no entities remain
 *    ("Sweatshirts &amp; Hoodies" → "Sweatshirts & Hoodies").
 *  - products.description: stored HTML → only collapse multi-encoded
 *    chains to a single level ("&amp;amp;" → "&amp;"); a full decode
 *    could corrupt the markup (e.g. "&lt;3" → "<3").
 *
 * Reads the LOCAL D1 copy, writes migrations/0003_fix_entities.sql with
 * id-targeted UPDATEs. Run: npx tsx scripts/fix-entities.ts
 */
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "migrations", "0003_fix_entities.sql");

const NAMED: Record<string, string> = {
  amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ",
};

function decodeOnce(s: string): string {
  return s.replace(/&([a-zA-Z]+|#\d+|#x[0-9a-fA-F]+);/g, (m, e) => {
    if (e[0] === "#") {
      const code = e[1].toLowerCase() === "x" ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : m;
    }
    return NAMED[e.toLowerCase()] ?? m;
  });
}

/** Full decode for plain-text fields: repeat until stable. */
function decodeFully(s: string): string {
  let prev = s;
  for (let i = 0; i < 10; i++) {
    const next = decodeOnce(prev);
    if (next === prev) return next;
    prev = next;
  }
  return prev;
}

/** For HTML fields: strip one "&amp;" layer wherever it wraps another entity, until stable. */
function collapseToSingle(s: string): string {
  const re = /&amp;(?=[a-zA-Z]+;|#\d+;|#x[0-9a-fA-F]+;)/g;
  let prev = s;
  for (let i = 0; i < 10; i++) {
    const next = prev.replace(re, "&");
    if (next === prev) return next;
    prev = next;
  }
  return prev;
}

function q(table: string, cols: string, where: string): any[] {
  const out = execFileSync(
    "npx",
    ["wrangler", "d1", "execute", "fomawebsitedatabase", "--local", "--json",
     "--command", `SELECT ${cols} FROM ${table} WHERE ${where}`],
    { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
  return JSON.parse(out)[0].results;
}

const sqlStr = (v: string) => `'${v.replace(/'/g, "''")}'`;

const updates: string[] = [];
const samples: string[] = [];

// names: any entity-looking content
for (const table of ["categories", "products"] as const) {
  const rows = q(table, "id, name", `name LIKE '%&%'`);
  for (const r of rows) {
    const fixed = decodeFully(r.name);
    if (fixed !== r.name) {
      updates.push(`UPDATE ${table} SET name = ${sqlStr(fixed)} WHERE id = ${r.id};`);
      samples.push(`${table}#${r.id}: ${JSON.stringify(r.name)} → ${JSON.stringify(fixed)}`);
    }
  }
}

// descriptions: only true multi-encoded chains
const descRows = q("products", "id, description", `description LIKE '%&amp;amp;%'`);
for (const r of descRows) {
  const fixed = collapseToSingle(r.description);
  if (fixed !== r.description) {
    updates.push(`UPDATE products SET description = ${sqlStr(fixed)}, updated_at = updated_at WHERE id = ${r.id};`);
    const i = r.description.indexOf("&amp;amp;");
    samples.push(`products#${r.id} (description, excerpt): ${JSON.stringify(r.description.slice(i - 20, i + 30))} → ${JSON.stringify(fixed.slice(Math.max(0, i - 20), i + 22))}`);
  }
}

fs.writeFileSync(
  OUT,
  [
    "-- 0003_fix_entities.sql — decode HTML entities from OpenCart data",
    "-- names: fully decoded to plain text; descriptions: multi-encoding collapsed to single level.",
    "-- Generated by scripts/fix-entities.ts",
    "",
    ...updates,
    "",
  ].join("\n"),
);

console.log(`UPDATE statements: ${updates.length} → ${OUT}`);
console.log("--- samples ---");
for (const s of samples) console.log(s);
