-- 0003_fix_entities.sql — decode HTML entities from OpenCart data
-- names: fully decoded to plain text; descriptions: multi-encoding collapsed to single level.
-- Generated by scripts/fix-entities.ts

UPDATE categories SET name = 'Sweatshirts & Hoodies' WHERE id = 224;
UPDATE products SET name = 'Personalized Disney Mickey & Friends Christmas Family Matching Sweatshirt,Custom All Characters Disneyland Xmas Hoodie,Disneyland Christmas' WHERE id = 434;
UPDATE products SET name = 'Just Bee You Sweatshirt & Hoodie, Nature Lover Gift, Cute Sweatshirt' WHERE id = 435;
UPDATE products SET name = 'Sports Personalized Name & Number Blanket, Custom Sports Throw, Adults / Kids Blanket with Name,Custom School Team/Sport Team Unisex Blanket' WHERE id = 583;
UPDATE products SET name = 'Personalized Photo Woven Blanket, Custom 50"x60" Cotton Throw, Tapestry Vintage-Retro, Photo Woven Blanket Collage, Christmas Gift' WHERE id = 1143;
UPDATE products SET name = 'Custom Name M and M Candy Family Sweatshirt, M&M Candy Sweatshirt, Group Family Matching Sweatshirt, Birthday Family Sweatshirt' WHERE id = 1252;
UPDATE products SET name = 'Custom Name M and M Candy Family Shirt, Personalized M&M Candy T Shirt, Group Family Matching Shirt, Birthday Family Shirt' WHERE id = 1256;
UPDATE products SET name = 'Personalized 40oz  Tumbler With Handle & Straw, Custom Name Stainless Steel Engraved Cup, 40oz Travel Mug, Christmas Gift' WHERE id = 1301;
UPDATE products SET name = 'Custom Logo 40oz  Tumbler With Handle & Straw, Personalized 40oz Tumbler, Stainless Steel Laser Engraved Tumbler' WHERE id = 1302;
UPDATE products SET name = 'Car Christmas Ornament, Personalized Mr. & Mrs.Holiday Tree and Gifts Ornament with Custom Names, Custom Mr. and Mrs. Tree Christmas Ornament' WHERE id = 1417;
UPDATE products SET name = 'Snowflake Hoodie&Sweatshirt, Snow flake design sweater' WHERE id = 1466;
UPDATE products SET name = 'Custom Logo 40oz Tumbler With Handle, Personalized 40oz Tumbler with Handle &Straw, Custom Cup with Logo, Laser Engraved Tumbler, Bulk Order' WHERE id = 1715;
UPDATE products SET name = 'Personalized 40oz Tumbler with Handle & Straw, Custom Monogram Name Engraved Cup, 40 oz Travel Mug, Personalized Gift for Christmas Her' WHERE id = 1730;
UPDATE products SET name = 'Personalized 12 oz Wine Tumbler,  Custom Engraved Cup, Monogram & Unique Designs Wine Tumbler, Christmas Gift Wine Tumbler, Custom Logo Mug' WHERE id = 1738;
UPDATE products SET description = '&lt;p&gt;&lt;span style=&quot;font-size: 14px;&quot;&gt;Choose your t-shirt color, size, and design ﻿&amp; text color.&lt;br&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14px;&quot;&gt;Color disclaimer: Prints may appear smaller depending on the ordered shirt size.&lt;br&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14px;&quot;&gt;Fabrication: 50% cotton, 50% polyester.&lt;/span&gt;&lt;/p&gt;', updated_at = updated_at WHERE id = 481;
